apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: shimul921/spring-petclinic-v2
          args:
            - "java"
            - "-jar"
            - "my-spring-boot-app.jar"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  selector:
    app: spring-petclinic
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
